language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t dhrumilmevada/fib-react-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dhrumilmevada/fib-react-client npm run test

after_success:
  - docker build -t dhrumilmevada/fib-multi-cli ./client
  - docker build -t dhrumilmevada/fib-multi-nginx ./nginx
  - docker build -t dhrumilmevada/fib-multi-server ./server
  - docker build -t dhrumilmevada/fib-multi-worker ./worker
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker push dhrumilmevada/fib-multi-cli 
  - docker push dhrumilmevada/fib-multi-nginx
  - docker push dhrumilmevada/fib-multi-server
  - docker push dhrumilmevada/fib-multi-worker