version: "3"

services:
  client:
    image: "dhrumilmevada/fib-multi-cli"
    hostname: client
  api:
    image: "dhrumilmevada/fib-multi-server"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "dhrumilmevada/fib-multi-worker"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "dhrumilmevada/fib-multi-nginx"
    ports:
      - "80:80"
    hostname: nginx

  